name: 'Validation of Module installation'
description: 'Validate whether 3rd party modules are installed by proper way (not in app/code/ folder)'
inputs:
  allowed-vendors:
    description: 'Allowed Module Vendors'
    required: true
    default: |-
      Gene
      GeneSoftware
      JjCommerce
  allowed-modules:
    description: 'Allowed specific Modules'
    required: true
    default: |-
      Potato_Zendesk
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  image: 'index.js'
